manifest:manifest:

  defaults:  defaults:

    revision: v0.3    revision: v0.3

  remotes:  remotes:

    - name: zmkfirmware    - name: zmkfirmware

      url-base: https://github.com/zmkfirmware      url-base: https://github.com/zmkfirmware

    # Additional modules containing boards/shields/custom code can be listed here as well    # Additional modules containing boards/shields/custom code can be listed here as well

    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects

  projects:  projects:

    - name: zmk    - name: zmk

      remote: zmkfirmware      remote: zmkfirmware

      import: app/west.yml      import: app/west.yml

  self:  self:

    path: config    path: config

