# Copyright (c) 2025
# SPDX-License-Identifier: MIT

file_format: "1"
id: custom_keyboard
name: Custom Keyboard
type: shield
url: https://github.com/TigeyJewellAlibhai/lgk-zmk
requires: [pro_micro]
features:
  - keys
